title: Option-Pricing-Black-Scholes-Monte-Carlo
description: Quantitative finance project implementing option pricing using the Black-Scholes model, Option Greeks, and Monte Carlo simulations in Python.
theme: jekyll-theme-slate
